%This Script is used to simulate 3 mag sensors(HMC1051) , mounted on the three axes of X,Y,Z 
%Important thing to note is that the Voltage generated by the sensor is
%directly propotional to the mag field applied on that axis.Ie it is
%directly proportional to the magnitude of the mag field vector in that axis.Therefore
%we can safetly assume that the generated voltages are the constitutents
%of the eventual resultant mag field vector. Do note that we would use a
%calibration factor in real life to get the mag field measurement.
%% Sensor Simulation Parameters
params.Vbridge = 5;             % Bridge supply voltage [V]
params.sensitivity = 1.0;       % Sensitivity [mV/V/gauss]
params.offset_bias = 1.25;      % Offset error [mV/V]
params.nonlin_pctFS = 0.5;      % Linearity error (% of full-scale)
params.hysteresis_pctFS = 0.06; % Hysteresis error (% of full-scale)
params.repeat_pctFS = 0.05;     % Repeatability error (% of full-scale)
params.noise_density = 50;      % Noise density [nV/√Hz]
params.bandwidth = 10;          % Bandwidth [Hz]

%% Define Applied Magnetic Fields (in gauss)
%  applied magnetic fields along the CubeSat's axes.
% we assume constant fields for demonstration.
B_app_x = 2.0;    % X-axis applied magnetic field (gauss)
B_app_y = -1.5;   % Y-axis applied magnetic field (gauss)
B_app_z = 0.5;    % Z-axis applied magnetic field (gauss)

%% Simulate Sensor Outputs for Each Axis
Vx = simulate_HMC1051(B_app_x, params);
Vy = simulate_HMC1051(B_app_y, params);
Vz = simulate_HMC1051(B_app_z, params);

%% Combine Sensor Outputs into a Magnetic Field Vector
mag_vector = [Vx, Vy, Vz];

% Display the simulated sensor outputs (in mV)
fprintf('Simulated Sensor Outputs (mV):\n');
fprintf('X-axis: %.3f mV\n', Vx);
fprintf('Y-axis: %.3f mV\n', Vy);
fprintf('Z-axis: %.3f mV\n', Vz);

%% Plot 
figure;
quiver3(0, 0, 0, Vx, Vy, Vz, 'LineWidth', 2, 'MaxHeadSize', 0.5);
xlabel('X-axis (mV)');
ylabel('Y-axis (mV)');
zlabel('Z-axis (mV)');
title('Simulated 3-Axis Magnetic Field Vector from HMC1051 Sensors');
grid on;
axis equal;
